Localize timezone to None
Fixes errors like:

    /home/amacdon/anaconda3-201901/envs/gtc/lib/python3.8/site-packages/phildb/writer.py:65: UserWarning: Converting to Period representation will drop timezone information.
      start_date.to_period(freqstr)
    Traceback (most recent call last):
      File "/home/amacdon/anaconda3-201901/envs/gtc/bin/gtc", line 11, in <module>
        load_entry_point('github-traffic-collector', 'console_scripts', 'gtc')()
      File "/home/amacdon/code/github_traffic_collector/github_traffic_collector/gtc.py", line 141, in main
        db.write(repo_name, 'D', views_df['count'], measurand = 'V')
      File "/home/amacdon/anaconda3-201901/envs/gtc/lib/python3.8/site-packages/phildb/database.py", line 364, in write
        modified = writer.write(
      File "/home/amacdon/anaconda3-201901/envs/gtc/lib/python3.8/site-packages/phildb/writer.py", line 179, in write
        return write_regular_data(tsdb_file, series)
      File "/home/amacdon/anaconda3-201901/envs/gtc/lib/python3.8/site-packages/phildb/writer.py", line 213, in write_regular_data
        if start_date < first_record_date:
      File "pandas/_libs/tslibs/c_timestamp.pyx", line 122, in pandas._libs.tslibs.c_timestamp._Timestamp.__richcmp__
      File "pandas/_libs/tslibs/c_timestamp.pyx", line 185, in pandas._libs.tslibs.c_timestamp._Timestamp._assert_tzawareness_compat
    TypeError: Cannot compare tz-naive and tz-aware timestamps